### ISSUE TITLE
Bug - Videos uploaded as mkv have distorted thumbnails

### ISSUE THREAD

**Issue by tissole** [SpEcHiDe/UploadGram#11]
The image is squeezed vertically, does not have a 16:9 aspect ratio. I resolved this by changing lines 176 and 177 from upload.py from 
```
        width = 0
        height = 0
```
```
to 
        width = 1280
        height = 720
```

**Comment by SpEcHiDe** [comment]
This depends how the thumbnail is displayed in the different clients. Even official telegram.org/apps have different behaviour,
