### ISSUE TITLE
Console Progress Bar not accurate

### ISSUE THREAD

**Issue by BetaTester41** [SpEcHiDe/UploadGram#14]
When using the console progress bar, it seems like the upload speed is incorrect. Also, after a few seconds, I quickly exceeds the original file size.
![image](https://user-images.githubusercontent.com/76068161/155635961-def28d42-39de-4a32-b5ef-580cda394861.png)

The original file size:
![image](https://user-images.githubusercontent.com/76068161/155636160-5f21d4f7-fbf2-49bb-af7c-4fd2915a46be.png)

For a fact, I know my (slow) internet can only reach 10MiB/s. The original file size was: 1.95GB, not the 2+ GB it's upload. The message progress bar is working correctly.

**Comment by SpEcHiDe** [comment]
duplicate #9
