### ISSUE TITLE
Files of exactly 2 GB in size are not uploaded

### ISSUE THREAD

**Issue by tissole** [SpEcHiDe/UploadGram#15]
I found that the culprit is in line 60 from upload.py
`        elif os.stat(current_name).st_size < TG_MAX_FILE_SIZE:`
It should be
`        elif os.stat(current_name).st_size <= TG_MAX_FILE_SIZE:`

**Comment by SpEcHiDe** [comment]
I don't think so 😅🤔

**Comment by SpEcHiDe** [comment]
Can you do a pr, please?

**Comment by tissole** [comment]
Never done it, I don't know how.
