### ISSUE TITLE
Question - Why temporary sessions?

### ISSUE THREAD

**Issue by tissole** [SpEcHiDe/UploadGram#21]
Thanks for updating to Pyrogram V2 and supporting the new premium features. Now the script asks for credentials every time it starts. Before the credentials were asked only once. Is there a reason for this choice? I change it to not use in memory sessions, but cannot find the session file in `~/.config/uploadgram/`. Where it is stored?

**Comment by SpEcHiDe** [comment]
Sorry, it was my mistake 😑


Will fix.
