### ISSUE TITLE
Feature request - Option to upload directly from cloud drives

### ISSUE THREAD

**Issue by tissole** [SpEcHiDe/UploadGram#7]
Since uploading from mount drives is possible, I think that an option to upload directly should be implemented. It will run more smoothly because reading from a mounted drive is adding another layer of complexity. There are bots that can upload from TG to cloud drives, so why not doing in reverse, uploading from a Google Drive or a Mega Drive to TG?

It will make life easier for users to transfer files from other clouds to TG on the fly without downloading them first, so no usage of local drive space, and when deploying to a VPS it will use that bandwidth which is greater than most users have at home.

**Comment by SpEcHiDe** [comment]
I think this would be out of scope. I am extremely sorry, but I cannot add this feature.

**Comment by tissole** [comment]
OK. If it works from mounted drives I'm happy :)
